apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: kworker1
  taints: null
  kubeletExtraArgs:
    node-ip: 192.168.99.21
  
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    token: mrandy.7eab8b1a3ebd6cb2
    apiServerEndpoint: 192.168.99.20:6443
    caCertHashes: 
      - sha256:64d6bd70aa93773803cf0fcc36abc7a1841a76d8769831515cbbb5623f46e606
